FROM  python
#  from  will pull  python  docker image  from  docker hub 
COPY  ashu.py  /tmp/ashu.py 
#  from  host  to  docker  image  copy 
#CMD  python   /tmp/ashu.py  
#  this will be  default  parent  process
ENTRYPOINT  python   /tmp/ashu.py  
#  this will be  default  parent  process  and  we can  not replace as a argument 
